### ISSUE TITLE
Don't strip music symbols

### ISSUE THREAD

**Issue by rlaphoenix** [nyuszika7h/pysdhstrip#1]
Typically in non-SDH subtitles, you would have `♪ ♪` to indicate that music or song is happening, similar to e.g., `♪ lyrics here ♪`, just without the lyrics. This is to indicate that it is not quiet, but songs are being played.

The code you have on line 72-73 is removing what would be those lines, but also not handling lines that have lyrics.

https://github.com/nyuszika7h/pysdhstrip/blob/f9ad3b19ead1409e521afa467b2523e05d370d25/pysdhstrip/pysdhstrip.py#L72-L73

**Comment by nyuszika7h** [comment]
This is working as intended. I think it's unnecessary to indicate music when there's no lyrics (that's what SDH subtitles are for), but lyrics can be important to the plot in some cases and there's no way to automatically determine whether it's important or not.
